/* Copyright (C) 2026 Qore Technologies, s.r.o.
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */
package org.qore.jni.test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.net.URLClassLoader;
import java.net.URL;

import net.bytebuddy.jar.asm.ClassReader;
import net.bytebuddy.jar.asm.ClassWriter;
import net.bytebuddy.jar.asm.ClassVisitor;
import net.bytebuddy.jar.asm.MethodVisitor;
import net.bytebuddy.jar.asm.Opcodes;
import org.qore.jni.JavaClassBuilder;
import org.qore.jni.QoreObjectBase;
import org.qore.jni.QoreURLClassLoader;

/** Keeps generated bytecode and Java classes alive without retaining a Qore Program. */
public class GeneratedBindings {
    private static final String PREFIX = "qore.EmbeddedBindingTest.";
    private final byte[][] bytes;
    private final Class<?>[] classes;
    private final long programId;
    private final long methodHandle;
    private final long functionHandle;
    private final long constantHandle;

    private static class Loader extends ClassLoader {
        Loader() {
            super(GeneratedBindings.class.getClassLoader());
        }
        Class<?> define(byte[] bytes) {
            return defineClass(null, bytes, 0, bytes.length);
        }
    }

    public GeneratedBindings(long programId, byte[] constants, byte[] calls, byte[] functions, byte[] nsConstants) {
        this.programId = programId;
        bytes = new byte[][] {constants, calls, functions, nsConstants};
        Loader loader = new Loader();
        classes = new Class<?>[bytes.length];
        for (int i = 0; i < bytes.length; ++i) {
            classes[i] = loader.define(bytes[i]);
        }
        methodHandle = handle(calls, "value");
        functionHandle = handle(functions, "plus");
        constantHandle = handle(constants, "<clinit>");
    }

    private static long handle(byte[] bytes, String method) {
        List<Long> handles = new ArrayList<>();
        new ClassReader(bytes).accept(new ClassVisitor(Opcodes.ASM9) {
            @Override
            public MethodVisitor visitMethod(int access, String name, String descriptor, String signature,
                    String[] exceptions) {
                if (!name.equals(method)) {
                    return null;
                }
                return new MethodVisitor(Opcodes.ASM9) {
                    @Override
                    public void visitLdcInsn(Object value) {
                        if (value instanceof Long && (Long)value < 0) {
                            handles.add((Long)value);
                        }
                    }
                };
            }
        }, 0);
        if (handles.isEmpty()) {
            throw new AssertionError("No registered handle in " + method);
        }
        return handles.get(0);
    }

    public Object constant() throws Throwable {
        return classes[0].getField("Value").get(null);
    }

    public Object namespaceConstant() throws Throwable {
        return classes[3].getField("NsValue").get(null);
    }

    public Object function(long arg) throws Throwable {
        return classes[2].getMethod("plus", long.class).invoke(null, arg);
    }

    public Object staticCall(long arg) throws Throwable {
        return classes[1].getMethod("twice", long.class).invoke(null, arg);
    }

    public Object normalCall(long arg) throws Throwable {
        QoreObjectBase obj = (QoreObjectBase)classes[1].getConstructor().newInstance();
        try {
            return classes[1].getMethod("value", long.class).invoke(obj, arg);
        } finally {
            obj.destroy();
        }
    }

    private interface ThrowingCall {
        Object call() throws Throwable;
    }

    private static void rejected(ThrowingCall call, String expected) throws Throwable {
        try {
            call.call();
        } catch (Throwable e) {
            Throwable cause = e;
            while (cause.getCause() != null) {
                cause = cause.getCause();
            }
            if (cause.getMessage() != null && cause.getMessage().contains(expected)) {
                return;
            }
            throw new AssertionError("Expected " + expected + ", got " + e, e);
        }
        throw new AssertionError("Invalid generated binding was accepted");
    }

    public int expired() throws Throwable {
        String expected = "no longer available";
        rejected(this::constant, expected);
        rejected(this::namespaceConstant, expected);
        rejected(() -> function(1), expected);
        rejected(() -> staticCall(1), expected);
        rejected(() -> classes[1].getConstructor().newInstance(), expected);
        // The object is intentionally null: the expired method must be rejected
        // before even considering object or method metadata.
        rejected(() -> JavaClassBuilder.doNormalCall("value", 0, methodHandle, 0), expected);
        return 6;
    }

    public int invalid() throws Throwable {
        for (long invalid : new long[] {0, 1, 0x12345678abcdefL, Long.MAX_VALUE}) {
            rejected(() -> JavaClassBuilder.getConstantValue(programId, invalid), "no longer available");
            rejected(() -> JavaClassBuilder.doFunctionCall(programId, invalid, 0), "no longer available");
            rejected(() -> JavaClassBuilder.doNormalCall("value", 0, invalid, 0), "no longer available");
            rejected(() -> JavaClassBuilder.doStaticCall("twice", invalid, programId, invalid, 0),
                "no longer available");
            rejected(() -> classes[1].getConstructor(long.class, long.class, long.class, Object[].class)
                .newInstance(invalid, 0L, 0L, null), "no longer available");
        }
        rejected(() -> JavaClassBuilder.getConstantValue(programId + (1L << 32), constantHandle), "Program ID");
        rejected(() -> JavaClassBuilder.doFunctionCall(0, functionHandle, 0), "Program ID");
        rejected(() -> JavaClassBuilder.getConstantValue(programId, functionHandle), "no longer available");
        rejected(() -> JavaClassBuilder.doFunctionCall(programId, functionHandle, 1), "Invalid variant");
        rejected(() -> JavaClassBuilder.doNormalCall("value", 0, methodHandle, 0), "Invalid object");
        return 25;
    }

    public static int legacyInitializer() throws Throwable {
        // Recreate the old persisted bytecode, including its positive raw pointer
        // literals, instead of generating it through the updated native builder.
        String name = "qore/EmbeddedBindingTest/Legacy";
        ClassWriter writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        writer.visit(Opcodes.V21, Opcodes.ACC_PUBLIC, name, null, "java/lang/Object", null);
        writer.visitField(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL, "Value", "J", null, null)
            .visitEnd();
        MethodVisitor init = writer.visitMethod(Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        init.visitCode();
        init.visitLdcInsn(0x12345678abcdefL);
        init.visitLdcInsn(0x12345678123456L);
        init.visitMethodInsn(Opcodes.INVOKESTATIC, "org/qore/jni/JavaClassBuilder", "getConstantValue",
            "(JJ)Ljava/lang/Object;", false);
        init.visitTypeInsn(Opcodes.CHECKCAST, "java/lang/Long");
        init.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/lang/Long", "longValue", "()J", false);
        init.visitFieldInsn(Opcodes.PUTSTATIC, name, "Value", "J");
        init.visitInsn(Opcodes.RETURN);
        init.visitMaxs(0, 0);
        init.visitEnd();
        writer.visitEnd();
        Class<?> legacy = new Loader().define(writer.toByteArray());
        rejected(() -> Class.forName(legacy.getName(), true, legacy.getClassLoader()), "no longer available");
        return 1;
    }

    public String persist() throws Exception {
        Path jar = Files.createTempFile("jni-generated-bindings-", ".jar");
        try {
            try (JarOutputStream out = new JarOutputStream(Files.newOutputStream(jar))) {
                for (int i = 0; i < classes.length; ++i) {
                    out.putNextEntry(new JarEntry(classes[i].getName().replace('.', '/') + ".class"));
                    out.write(bytes[i]);
                    out.closeEntry();
                }
            }
            return jar.toString();
        } catch (Exception e) {
            Files.deleteIfExists(jar);
            throw e;
        }
    }

    public static void deleteJar(String path) throws Exception {
        Files.deleteIfExists(Path.of(path));
    }

    public static void checkJar(String path) throws Throwable {
        try (URLClassLoader loader = new URLClassLoader(new URL[] {Path.of(path).toUri().toURL()},
                GeneratedBindings.class.getClassLoader())) {
            // Inspecting names without initialization is safe in a foreign process.
            Class<?> constants = Class.forName(PREFIX + "Constants", false, loader);
            if (!constants.getDeclaredField("Value").getType().equals(long.class)) {
                throw new AssertionError("Constant signature changed");
            }
            rejected(() -> Class.forName(constants.getName(), true, loader), "no longer available");
            rejected(() -> Class.forName(PREFIX + "$Constants", true, loader), "no longer available");
            Class<?> calls = Class.forName(PREFIX + "Calls", true, loader);
            rejected(() -> calls.getMethod("twice", long.class).invoke(null, 2L), "no longer available");
            rejected(() -> calls.getConstructor().newInstance(), "no longer available");
            Class<?> functions = Class.forName(PREFIX + "$Functions", true, loader);
            rejected(() -> functions.getMethod("plus", long.class).invoke(null, 2L), "no longer available");
        }
        System.out.println("Persisted generated bindings rejected safely");
    }
}
