package org.qore.jni;

import java.io.InputStream;
/**
 * A JavaFileObject interface
 */
public interface QoreJavaFileObject {
    /**
     * @return the byte code generated by the compiler
     */
    public byte[] getByteCode();
}

